#!/bin/bash

# First argument is the directory with temponym files
# populated by the script "chronontology_temponyms_export.py"
# or generated by "format_resource_files_from_temponym_translations.sh"
dir_temponym_files="${1}"

# Second argument is the directory of heideltime to plant the resource files in
dir_heideltime_app="${2}"

# replace pipe chars in the automatically created patterns as they confuse heideltime
sed -i 's/\s*|//g' "$dir_temponym_files"/*

# copy the temponym resource files
cp_resource() {
    cp "${1}" "${dir_heideltime_app}/resources/${2}/${3}/resources_${3}_${4}TemponymChronontology.txt"
}

# copy the resource files extracted from chronontology
cp_resource "${dir_temponym_files}/de_repattern.txt" "german"  "repattern" "re"
cp_resource "${dir_temponym_files}/en_repattern.txt" "english" "repattern" "re"
cp_resource "${dir_temponym_files}/es_repattern.txt" "spanish" "repattern" "re"
cp_resource "${dir_temponym_files}/fr_repattern.txt" "french"  "repattern" "re"
cp_resource "${dir_temponym_files}/it_repattern.txt" "italian" "repattern" "re"

cp_resource "${dir_temponym_files}/de_norm.txt" "german"  "normalization" "norm"
cp_resource "${dir_temponym_files}/en_norm.txt" "english" "normalization" "norm"
cp_resource "${dir_temponym_files}/es_norm.txt" "spanish" "normalization" "norm"
cp_resource "${dir_temponym_files}/fr_norm.txt" "french"  "normalization" "norm"
cp_resource "${dir_temponym_files}/it_norm.txt" "italian" "normalization" "norm"

# put temponym rules into place (same rule for both languages)
write_rule_if_not_exists() {
    # The rule uses heideltime's regex-syntax to link to the relevant pattern and normalization functions
    local rule='RULENAME="temponym_chronontology_1",EXTRACTION="%reTemponymChronontology",NORM_VALUE="%normTemponymChronontology(group(1))"'
    local file=${1}
    # Write the rule only if grep doesn't find its name (or the file doesn't exist)
    grep -q "temponym_chronontology_1" "$file" || echo "$rule" >> "$file"
}

# write rules to include the temponym files for the chronontology export
write_rule_if_not_exists "${dir_heideltime_app}/resources/english/rules/resources_rules_temponymrules.txt"
write_rule_if_not_exists "${dir_heideltime_app}/resources/german/rules/resources_rules_temponymrules.txt"
write_rule_if_not_exists "${dir_heideltime_app}/resources/spanish/rules/resources_rules_temponymrules.txt"
write_rule_if_not_exists "${dir_heideltime_app}/resources/french/rules/resources_rules_temponymrules.txt"
write_rule_if_not_exists "${dir_heideltime_app}/resources/italian/rules/resources_rules_temponymrules.txt"
